# Generated by Django 4.0.6 on 2022-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accId',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
