# Generated by Django 4.0.6 on 2022-08-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_account_accid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accId',
        ),
    ]
