# Generated by Django 4.0.6 on 2022-08-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_role1_accid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('roleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='role1',
            name='accId',
        ),
        migrations.DeleteModel(
            name='Account1',
        ),
        migrations.DeleteModel(
            name='Role1',
        ),
    ]
